### ISSUE TITLE
'Go' Search May Be Matching Incorrectly

### ISSUE THREAD

**Issue by rrgayhart** [LookingForMe/lookingfor#62] opened 2016-04-20 21:59 UTC
Searching for Go jobs is difficult in Authentic Jobs and StackOverflow since they are essentially searching the title and description for the word 'go'

Acceptance Criteria:
- Look at records tagged for Go
  - Find any records that seem to be matching incorrectly
    - If incorrect match found, add a test case and beef up regex or other matching used in the specific service that found that job

**Comment by Salvi6God** [comment] 2016-07-19 01:20
I just spent the past couple hours reviewing the code and I do not believe that we are matching job results incorrectly when we search for technologies that match with "Go". For example, on the "stack_overflow.rb" file there's a method called "generate_raw_technologies" where it uses Nokogiri's ".css" method that looks specifically within any tag called "category" and looks into its text that decides whether or not the language being searched for exists. 

I ended up making sure that the way we were scoping it down with Nokogiri was valid by reading the docs and it turns out that it is. 

Let me know if my explanation is good enough to close this issue @rrgayhart @JaredRoth

**Comment by JaredRoth** [comment] 2016-07-20 19:02
As @rrgayhart said, without the bug reporter referencing any examples or way to reproduce the issue, there's not much we can do here. I am hesitant to close it personally, though, because I didn't open it and am not as intimately familiar with what's going on.

**Comment by Salvi6God** [comment] 2016-07-20 19:09
We should discuss this in our stand-up today to decide the fate of this issue @JaredRoth. Personally, I also believe this should be closed since there's other issues to focus on and I did spend hours on my part checking out that we were pulling the right things.

**Closed** 2016-07-21 00:26 UTC
Labels: bug, ready-for-work!
